config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'home#index'
  resources :taxes, :customers, :invoices
  devise_for :users

  resources :invoice_items, only: [], param: :index do
    member do
      delete '(:id)' => 'invoice_items#destroy', as: ''
      post '/' => 'invoice_items#create'
    end
  end
end

app/models/application_record.rb
# frozen_string_literal: true

# ApplicationRecord
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/customer.rb
# frozen_string_literal: true

# Customer
class Customer < ApplicationRecord
  validates :name, :fiscal_id, presence: true
  validates :fiscal_id, format: { with: /\A[a-zA-Z0-9]*\z/, message: 'no special characters allowed' }

  has_many :invoices, dependent: :destroy
end

app/models/invoice.rb
# frozen_string_literal: true

# app/models/invoice.rb
class Invoice < ApplicationRecord
  belongs_to :customer
  has_many :invoice_items, dependent: :destroy
  validates :invoice_date, presence: true

  accepts_nested_attributes_for :invoice_items, reject_if: :all_blank, allow_destroy: true

  def calculate_sum
    self.total_gross = invoice_items.map(&:item_total_with_tax).sum.to_f
    self.total_taxes = invoice_items.map(&:tax_amount).sum.to_f
    self.total_net = invoice_items.map(&:item_total).sum.to_f
  end
end

app/models/invoice_item.rb
# frozen_string_literal: true

# app/models/invoice_item.rb
class InvoiceItem < ApplicationRecord
  belongs_to :tax
  belongs_to :invoice

  validates_presence_of :description, message: "can't be blank"

  before_save :calculate_total

  def calculate_total
    self.item_total = (units * unit_cost).to_f
    self.tax_amount = (item_total / 100) * tax.percentage
    self.item_total_with_tax = item_total + tax_amount
  end
end

app/models/tax.rb
# frozen_string_literal: true

# Tax
class Tax < ApplicationRecord
  validates :tax_name, :percentage, presence: true, uniqueness: true
  has_many :invoice_items
end

app/models/user.rb
# frozen_string_literal: true

# User
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one_attached :avatar
end

app/controllers/application_controller.rb
# frozen_string_literal: true

# ApplicationController
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit :account_update, keys: %i[name email avatar]
  end
end

app/controllers/customers_controller.rb
# frozen_string_literal: true

# CustomersController
class CustomersController < ApplicationController
  before_action :authenticate_user!
  before_action :set_customer, only: %i[show edit update destroy]

  def index
    @customers = Customer.paginate(page: params[:page], per_page: 5)
  end

  def show; end

  def new
    @customer = Customer.new
  end

  def edit; end

  def create
    @customer = Customer.new(customer_params)

    respond_to do |format|
      if @customer.save
        format.html { redirect_to customer_url(@customer), notice: 'Customer was successfully created.' }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @customer.update(customer_params)
        format.html { redirect_to customer_url(@customer), notice: 'Customer was successfully updated.' }
      else
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @customer.destroy

    respond_to do |format|
      format.html { redirect_to customers_url, notice: 'Customer was successfully destroyed.' }
    end
  end

  private

  def set_customer
    @customer = Customer.find(params[:id])
  end

  def customer_params
    params.require(:customer).permit(:name, :fiscal_id)
  end
end

app/controllers/home_controller.rb
# frozen_string_literal: true

# HomeController
class HomeController < ApplicationController
  def index; end
end

app/controllers/invoice_items_controller.rb
# app/controllers/invoice_items_controller.rb
class InvoiceItemsController < ApplicationController
  before_action :set_invoice

  def new; end

  def destroy; end

  private

  def invoice_params
    params.require(:invoice)
          .permit(:customer_id, :invoice_date,
                  :total_gross, :total_net, :total_taxes,
                  invoice_items_attributes: %i[id description units item_index unit_cost tax_id _destroy])
  end

  def set_invoice
    @invoice = Invoice.new(invoice_items: [InvoiceItem.new])
  end
end

app/controllers/invoices_controller.rb
# frozen_string_literal: true

# InvoicesController
class InvoicesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_invoice, only: %i[show edit update destroy]

  def index
    @invoices = Invoice.includes(:customer).paginate(page: params[:page], per_page: 5)
  end

  def show; end

  def new
    @invoice = Invoice.new
  end

  def create
    @invoice = Invoice.new(invoice_params)

    respond_to do |format|
      if @invoice.save
        @invoice.update(
          total_gross: @invoice.invoice_items.sum(:item_total_with_tax).to_f,
          total_taxes: @invoice.invoice_items.sum(:tax_amount).to_f,
          total_net: @invoice.invoice_items.sum(:item_total).to_f
        )
        format.html { redirect_to invoice_url(@invoice), notice: 'Invoice was successfully created.' }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  private

  def set_invoice
    @invoice = Invoice.find(params[:id])
  end

  def invoice_params
    params.require(:invoice)
          .permit(:customer_id, :invoice_date, :total_gross,
                  :total_net, :total_taxes,
                  invoice_items_attributes: [
                    :id, :description, :units, :unit_cost,
                    :tax_id, :item_total, :tax_amount,
                    :item_total_with_tax,
                    :_destroy])
  end
end

app/controllers/taxes_controller.rb
# frozen_string_literal: true

# TaxesController
class TaxesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_tax, only: %i[show edit update destroy]

  def index
    @taxes = Tax.paginate(page: params[:page], per_page: 5)
  end

  def show; end

  def new
    @tax = Tax.new
  end

  def edit; end

  def create
    @tax = Tax.new(tax_params)

    respond_to do |format|
      if @tax.save
        format.html { redirect_to tax_url(@tax), notice: 'Tax was successfully created.' }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @tax.update(tax_params)
        format.html { redirect_to tax_url(@tax), notice: 'Tax was successfully updated.' }
      else
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @tax.destroy

    respond_to do |format|
      format.html { redirect_to taxes_url, notice: 'Tax was successfully destroyed.' }
    end
  end

  private

  def set_tax
    @tax = Tax.find(params[:id])
  end

  def tax_params
    params.require(:tax).permit(:tax_name, :percentage)
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

# ApplicationHelper
module ApplicationHelper
end

app/helpers/customers_helper.rb
# frozen_string_literal: true

# CustomerHelper
module CustomersHelper
end

app/helpers/home_helper.rb
# frozen_string_literal: true

# HomeHelper
module HomeHelper
end

app/helpers/invoices_helper.rb
# frozen_string_literal: true

# InvoicesHelper
module InvoicesHelper
  def select_options_for_taxes
    options = ''
    taxes = Tax.select(:id, :tax_name, :percentage).as_json
    taxes.each do |opt|
      options += option_tag(opt['id'], opt['tax_name'], opt['percentage'])
    end
    options.html_safe
  end

  def option_tag(value, label, data)
    "<option data-percentage=#{data} value=#{value}>#{label}</option>"
  end
end

app/helpers/taxes_helper.rb
# frozen_string_literal: true

# TaxesHelper
module TaxesHelper
end

app/views/customers/_customer.html.erb
<div id="<%= dom_id customer %>">
  <p class="my-5">
    <strong class="block font-medium mb-1">Name:</strong>
    <%= customer.name %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Fiscal:</strong>
    <%= customer.fiscal_id %>
  </p>

  <% if action_name != "show" %>
    <%= link_to "Show this customer", customer, class: "rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <%= link_to 'Edit this customer', edit_customer_path(customer), class: "rounded-lg py-3 ml-2 px-5 bg-gray-100 inline-block font-medium" %>
    <hr class="mt-6">
  <% end %>
</div>

app/views/customers/_form.html.erb
<%= form_with(model: customer, class: "contents") do |form| %>
  <% if customer.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(customer.errors.count, "error") %> prohibited this customer from being saved:</h2>

      <ul>
        <% customer.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :name %>
    <%= form.text_field :name, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :fiscal_id %>
    <%= form.text_field :fiscal_id, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="inline">
    <%= form.submit class: "rounded-lg py-3 px-5 bg-orange-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/customers/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing customer</h1>

  <%= render "form", customer: @customer %>

  <%= link_to "Show this customer", @customer, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Back to customers", customers_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/customers/index.html.erb
<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Customers</h1>
    <%= link_to 'New customer', new_customer_path, class: "rounded-lg py-3 px-5 bg-orange-600 text-white block font-medium" %>
  </div>

  <div id="customers" class="min-w-full">
    <%= render @customers %>
    <%= will_paginate @customers %>
  </div>
</div>

app/views/customers/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New customer</h1>

  <%= render "form", customer: @customer %>

  <%= link_to 'Back to customers', customers_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/customers/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <%= render @customer %>

    <%= link_to 'Edit this customer', edit_customer_path(@customer), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <div class="inline-block ml-2">
      <%= button_to 'Destroy this customer', customer_path(@customer), method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
    </div>
    <%= link_to 'Back to customers', customers_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  </div>
</div>

app/views/home/index.html.erb
<div>
  <h2 class="font-bold text-4xl">Welcome to Invoice Management system</h1>
</div>

app/views/invoice_items/create.turbo_stream.erb
<%# app/views/invoice_items/create.turbo_stream.erb %>
<%= fields model: @invoice do |form| %>
  <%= form.fields_for :invoice_items, child_index: (params[:index].to_i + 1) do |invoice_item_form| %>
    <%= turbo_stream.replace "new-invoice_item" do %>
      <%= form.submit "+ New Invoice Item",
            formaction: invoice_item_path(invoice_item_form.index.to_i),
            formmethod: :post,
            formnovalidate: true,
            id: "new-invoice_item",
            class: "mb-6 text-orange-600 border border-orange-600 hover:bg-orange-600 hover:text-white active:bg-orange-600 font-bold uppercase px-8 py-3 rounded outline-none focus:outline-none mr-1 mb-1 ease-linear transition-all duration-150"
      %>
    <% end %>

    <%= turbo_stream.append "invoice_items" do %>
      <%= render "form", form: invoice_item_form %>
    <% end %>
  <% end %>
<% end %>

app/views/invoice_items/destroy.html.erb
<%= fields model: @invoice do |form| %>
  <%= form.fields_for :invoice_items, child_index: params[:index] do |invoice_item_form| %>
    <%= turbo_frame_tag "invoice_item_#{invoice_item_form.index}" do %>
      <%= invoice_item_form.hidden_field :id, value: params[:id] %>
      <%= invoice_item_form.hidden_field :_destroy, value: true %>
    <% end %>
  <% end %>
<% end %>

app/views/invoices/_form.html.erb
<div data-controller="invoice">
  <%= form_with model: invoice, class: "contents" do |form| %>
    <% if invoice.errors.any? %>
      <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
        <h2><%= pluralize(invoice.errors.count, "error") %> prohibited this invoice from being saved:</h2>

        <ul>
          <% invoice.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="grid gap-6 mb-6 md:grid-cols-2">
      <div>
        <label for="customer" class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">Customer</label>
        <%= form.select :customer_id, Customer.all.collect { |customer| [customer.name, customer.id] }, {}, { class: "bg-white border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-orange-500 focus:border-orange-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-orange-500 dark:focus:border-orange-500" } %>
      </div>
      <div>
        <label for="invoice_date" class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">Invoice Date</label>
        <%= form.date_field :invoice_date, { value: Time.now.strftime('%Y-%m-%d'), class: "bg-white border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-orange-500 focus:border-orange-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-orange-500 dark:focus:border-orange-500" } %>
      </div>
    </div>

    <%= turbo_frame_tag "hidden_fields" do %>
      <%= form.hidden_field :total_gross, value: 0.0, id: "total_gross_amount" %>
      <%= form.hidden_field :total_taxes, value: 0.0, id: "total_tax_amount" %>
      <%= form.hidden_field :total_net, value: 0.0, id: "total_net_amount" %>
    <% end %>

    <div id="invoice_items">
      <%= form.fields_for :invoice_items do |invoice_item_form| %>
        <%= render "invoice_items/form", form: invoice_item_form %>
      <% end %>
    </div>

    <%= form.submit "+ New Invoice Item",
      formaction: invoice_item_path(@invoice.invoice_items.size),
      formmethod: :post,
      formnovalidate: true,
      id: "new-invoice_item",
      class: "mb-6 text-orange-600 border border-orange-600 hover:bg-orange-600 hover:text-white active:bg-orange-600 font-bold uppercase px-8 py-3 rounded outline-none focus:outline-none mr-1 mb-1 ease-linear transition-all duration-150"
    %>

    <div class="">
      <%= form.submit class: "rounded-lg py-3 px-5 bg-orange-600 text-white inline-block font-medium cursor-pointer" %>
      <%= link_to 'Back to invoices', invoices_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    </div>
  <% end %>
</div>

app/views/invoices/index.html.erb
<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl text-orange-500">INVOICES</h1>
    <%= link_to 'New invoice', new_invoice_path, class: "rounded-lg py-3 px-5 bg-orange-600 text-white block font-medium" %>
  </div>

  <div id="invoices" class=" mt-10 min-w-full">
    <table class="table-auto w-full">
      <thead class="text-xs font-bold uppercase text-gray-600 bg-gray-50">
        <tr>
          <th class="p-2 whitespace-nowrap">
            <div class="font-bold text-left">Customer</div></th>
          <th class="p-2 whitespace-nowrap">
            <div class="font-bold text-left">Total Gross</div></th>
          <th class="p-2 whitespace-nowrap">
            <div class="font-bold text-left">Total Tax</div></th>
          <th class="p-2 whitespace-nowrap">
            <div class="font-bold text-left">Total Net</div></th>
          <th class="p-2 whitespace-nowrap">
            <div class="font-bold text-left">Action</div></th>
        </tr>
      </thead>
      <tbody class="text-sm divide-y divide-gray-100">
        <% @invoices.each do |invoice| %>
          <tr id="<%= dom_id invoice %>">
            <td class="p-2 whitespace-nowrap"><%= invoice.customer.name %></td>
            <td class="p-2 whitespace-nowrap"><%= invoice.total_gross.round(2) %></td>
            <td class="p-2 whitespace-nowrap"><%= invoice.total_taxes.round(2)  %></td>
            <td class="p-2 whitespace-nowrap"><%= invoice.total_net.round(2) %></td>
            <td class="p-2 whitespace-nowrap"><%= link_to "Show this invoice", invoice, class: "rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
    <div class="text-center my-4">
      <%= will_paginate @invoices %>
    </div>
  </div>
</div>

app/views/layouts/_sidebar.html.erb
<script src="https://cdn.jsdelivr.net/gh/alpinejs/alpine@v2.x.x/dist/alpine.min.js" defer></script>
<div class="md:flex flex-col md:flex-row md:min-h-screen w-full" style="width: 13%;
    float: left;">
  <div @click.away="open = false" class="flex flex-col w-full md:w-64 text-gray-700 bg-white dark-mode:text-gray-200 dark-mode:bg-gray-800 flex-shrink-0" x-data="{ open: false }">
    <div class="flex-shrink-0 px-8 py-4 flex flex-row items-center justify-between">
      <a href="/" style="color: #ff3004f7" class="text-lg font-semibold tracking-widest text-gray-900 uppercase rounded-lg dark-mode:text-white focus:outline-none focus:shadow-outline">Invoice Management</a>
      <button class="rounded-lg md:hidden rounded-lg focus:outline-none focus:shadow-outline" @click="open = !open">
        <svg fill="currentColor" viewBox="0 0 20 20" class="w-6 h-6">
          <path x-show="!open" fill-rule="evenodd" d="M3 5a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1zM3 10a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1zM9 15a1 1 0 011-1h6a1 1 0 110 2h-6a1 1 0 01-1-1z" clip-rule="evenodd"></path>
          <path x-show="open" fill-rule="evenodd" d="M4.293 4.293a1 1 0 011.414 0L10 8.586l4.293-4.293a1 1 0 111.414 1.414L11.414 10l4.293 4.293a1 1 0 01-1.414 1.414L10 11.414l-4.293 4.293a1 1 0 01-1.414-1.414L8.586 10 4.293 5.707a1 1 0 010-1.414z" clip-rule="evenodd"></path>
        </svg>
      </button>
    </div>
    <nav :class="{'block': open, 'hidden': !open}" class="flex-grow md:block px-4 pb-4 md:pb-0 md:overflow-y-auto">
      <% if current_user %>
        <%= link_to'Invoice', invoices_path,method: :delete, class: "block px-4 py-2 mt-2 text-sm font-semibold text-gray-900 bg-transparent rounded-lg dark-mode:bg-transparent dark-mode:hover:bg-gray-600 dark-mode:focus:bg-gray-600 dark-mode:focus:text-white dark-mode:hover:text-white dark-mode:text-gray-200 hover:text-gray-900 focus:text-gray-900 hover:bg-gray-200 focus:bg-gray-200 focus:outline-none focus:shadow-outline" %>
        <%= link_to'Customer', customers_path,method: :delete, class: "block px-4 py-2 mt-2 text-sm font-semibold text-gray-900 bg-transparent rounded-lg dark-mode:bg-transparent dark-mode:hover:bg-gray-600 dark-mode:focus:bg-gray-600 dark-mode:focus:text-white dark-mode:hover:text-white dark-mode:text-gray-200 hover:text-gray-900 focus:text-gray-900 hover:bg-gray-200 focus:bg-gray-200 focus:outline-none focus:shadow-outline" %>
        <%= link_to'Taxes', taxes_path,method: :delete, class: "block px-4 py-2 mt-2 text-sm font-semibold text-gray-900 bg-transparent rounded-lg dark-mode:bg-transparent dark-mode:hover:bg-gray-600 dark-mode:focus:bg-gray-600 dark-mode:focus:text-white dark-mode:hover:text-white dark-mode:text-gray-200 hover:text-gray-900 focus:text-gray-900 hover:bg-gray-200 focus:bg-gray-200 focus:outline-none focus:shadow-outline" %>
        <%= link_to "Edit Profile", edit_user_registration_path, class: "block px-4 py-2 mt-2 text-sm font-semibold text-gray-900 bg-transparent rounded-lg dark-mode:bg-transparent dark-mode:hover:bg-gray-600 dark-mode:focus:bg-gray-600 dark-mode:focus:text-white dark-mode:hover:text-white dark-mode:text-gray-200 hover:text-gray-900 focus:text-gray-900 hover:bg-gray-200 focus:bg-gray-200 focus:outline-none focus:shadow-outline" %>
        <%= link_to'Logout',destroy_user_session_path,method: :delete, class: "block px-4 py-2 mt-2 text-sm font-semibold text-gray-900 bg-transparent rounded-lg dark-mode:bg-transparent dark-mode:hover:bg-gray-600 dark-mode:focus:bg-gray-600 dark-mode:focus:text-white dark-mode:hover:text-white dark-mode:text-gray-200 hover:text-gray-900 focus:text-gray-900 hover:bg-gray-200 focus:bg-gray-200 focus:outline-none focus:shadow-outline" %>
      <% else %>
        <%= link_to "Login" , new_user_session_path, class: "block px-4 py-2 mt-2 text-sm font-semibold text-gray-900 bg-transparent rounded-lg dark-mode:bg-transparent dark-mode:hover:bg-gray-600 dark-mode:focus:bg-gray-600 dark-mode:focus:text-white dark-mode:hover:text-white dark-mode:text-gray-200 hover:text-gray-900 focus:text-gray-900 hover:bg-gray-200 focus:bg-gray-200 focus:outline-none focus:shadow-outline" %>
        <%= link_to 'Sign Up' ,new_user_registration_path, class: "block px-4 py-2 mt-2 text-sm font-semibold text-gray-900 bg-transparent rounded-lg dark-mode:bg-transparent dark-mode:hover:bg-gray-600 dark-mode:focus:bg-gray-600 dark-mode:focus:text-white dark-mode:hover:text-white dark-mode:text-gray-200 hover:text-gray-900 focus:text-gray-900 hover:bg-gray-200 focus:bg-gray-200 focus:outline-none focus:shadow-outline" %>
      <% end %>
    </nav>
  </div>
</div>

app/views/taxes/_tax.html.erb
<div id="<%= dom_id tax %>">
  <p class="my-5">
    <strong class="block font-medium mb-1">Tax name:</strong>
    <%= tax.tax_name %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Percentage:</strong>
    <%= tax.percentage %>
  </p>

  <% if action_name != "show" %>
    <%= link_to "Show this tax", tax, class: "rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <%= link_to 'Edit this tax', edit_tax_path(tax), class: "rounded-lg py-3 ml-2 px-5 bg-gray-100 inline-block font-medium" %>
    <hr class="mt-6">
  <% end %>
</div>

app/views/taxes/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing tax</h1>

  <%= render "form", tax: @tax %>

  <%= link_to "Show this tax", @tax, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Back to taxes", taxes_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/taxes/index.html.erb
<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Taxes</h1>
    <%= link_to 'New tax', new_tax_path, class: "rounded-lg py-3 px-5 bg-orange-600 text-white block font-medium" %>
  </div>

  <div id="taxes" class="min-w-full">
    <%= render @taxes %>
    <%= will_paginate @taxes %>
  </div>
</div>

app/views/taxes/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New tax</h1>

  <%= render "form", tax: @tax %>

  <%= link_to 'Back to taxes', taxes_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/taxes/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <%= render @tax %>

    <%= link_to 'Edit this tax', edit_tax_path(@tax), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <div class="inline-block ml-2">
      <%= button_to 'Destroy this tax', tax_path(@tax), method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
    </div>
    <%= link_to 'Back to taxes', taxes_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  </div>
</div>